###Post request to create a new user
POST http://localhost:8080/users/createUser
Content-Type: application/json

{
    "email": "sonam1231@gmail.com",
    "password": "Deep923451"

}
###Sign in request for user login
POST http://localhost:8080/users/signin
Content-Type: application/json

{
    "email": "sonam1231@gmail.com",
    "password":"Deep923451"
}

### Get current user
GET http://localhost:8080/users/whoAmI


###Signout request for user logout
POST http://localhost:8080/users/signout

###Get request to fetch all users

GET http://localhost:8080/users/getUser

###Get request to fetch user by id
GET http://localhost:8080/users/getUserById/3

###Delete request to delete user by id
DELETE   http://localhost:8080/users/removeUser/4

###Put request to update user by id
PUT  http://localhost:8080/users/updateUser/5
Content-Type: application/json

{
    "email": "Momma@gmail.com"
}